apiVersion: v2
name: metadata-extraktor
description: Extract data following a certain model from PDFs and create CSV from it.
keywords:
  - scdh
home: https://zivgitlab.uni-muenster.de/ULB/SCDH-Kooperation/metadata-extraktor
dependencies:
  - name: ulb-common
    repository: oci://harbor.uni-muenster.de/ulb-baseimages
    version: 1.x.x
maintainers:
  - name: Sebastian Stimberg
    email: sebastian.stimberg@uni-muenster.de
type: application
version: 0.2.0
appVersion: "1.16.0"
annotations:
  partof: scdh
  createdby: MircoWestermeier
  maintainedby: ULB-Digitale-Dienste
