apiVersion: v1
kind: Service
metadata:
  name: {{ include "metadata-extraktor.name" . }}
  annotations:
    # Introduce the service to Istio.
    # Otherwise it is unknown to the Istio Ingressgateway and not
    # accesable via the ingress.
    networking.istio.io/exportTo: istio-ingressgateway
  labels:
    {{- include "metadata-extraktor.labels" . | nindent 4 }}
spec:
  ports:
    - port: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "metadata-extraktor.selectorLabels" . | nindent 4 }}
