---
{{- if and .Values.image.imageCredentials.username .Values.image.imageCredentials.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metadata-extraktor.fullname" . }}-regcred
  labels:
    {{- include "metadata-extraktor.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "ulb.imagePullSecret" . }}
{{- end }}